<?php
/*=========================================================================
MIDAS Server
Copyright (c) Kitware SAS. 20 rue de la Villette. All rights reserved.
69328 Lyon, FRANCE.

See Copyright.txt for details.
This software is distributed WITHOUT ANY WARRANTY; without even
the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR
PURPOSE.  See the above copyright notices for more information.
=========================================================================*/
?>
<?php
$this->headScript()->appendFile(
  $this->apiWebroot . '/public/js/common/common.ajaxapi.js');
$this->headScript()->appendFile(
  $this->moduleWebroot . '/public/js/index/slicerpackages.index.js');
?>
<link type="text/css" rel="stylesheet" href="<?php echo $this->moduleWebroot.'/public/css/'.$this->moduleName ?>.index.css" />
<div class="viewMain">
  <div>
<?php
  foreach($this->packageSets as $folderName => $packageSet)
    {
    echo '<div class="releasefolder"><h3>'.$folderName.'</h3>';
    foreach($packageSet as $name => $package)
      {
      echo '<a href='.$this->webroot.'/download/?items='.$package->getItemId().'>'.$name.'</a><br />';
      }
    echo '<br /></div>';
    }
?>
  </div>
</div>

<?php echo $this->render('index/viewsidebar.phtml') ?>

