<?php
/*=========================================================================
MIDAS Server
Copyright (c) Kitware SAS. 20 rue de la Villette. All rights reserved.
69328 Lyon, FRANCE.

See Copyright.txt for details.
This software is distributed WITHOUT ANY WARRANTY; without even
the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR
PURPOSE.  See the above copyright notices for more information.
=========================================================================*/
?>
<?php
$this->headScript()->appendFile(
  $this->apiWebroot . '/public/js/common/common.ajaxapi.js');
$this->headScript()->appendFile(
  $this->moduleWebroot . '/public/js/index/slicerpackages.index.js');
?>
<link type="text/css" rel="stylesheet" href="<?php echo $this->moduleWebroot?>/public/css/slicerpackages.index.css" />
<div class="viewMain">
  <h3>Slicer Packages</h3>
  <div>
<?php
  foreach($this->folders as $folder)
    {
    echo '<div class="releasefolder"><h3>'.$folder->getName().'</h3>';
    foreach($folder->getItems() as $item)
      {
      echo '<a href='.$this->webroot.'/download/?items='.$item->getKey().'>'.$item->getName().'</a><br />';
      }
    echo '<br /></div>';
    }
?>
  </div>
</div>
<div class="viewSideBar">
  <div align="justify" class='sideElementFirst feedNotification'>
  This plugin enables the download of slicer packages in a nice, user-friendly
  way.
  </div>
  <div class="sideElementLast feedStats">
    <h1>Stats</h1>
    <?php
    echo "<ul>";
    echo "  <li>{$this->nPackages} {$this->t('package')}".(($this->nPackages>1)?'s':'')."</li>";
    echo "</ul>";
    ?>
  </div>
</div>
