<?php
/*=========================================================================
MIDAS Server
Copyright (c) Kitware SAS. 20 rue de la Villette. All rights reserved.
69328 Lyon, FRANCE.

See Copyright.txt for details.
This software is distributed WITHOUT ANY WARRANTY; without even
the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR
PURPOSE.  See the above copyright notices for more information.
=========================================================================*/
?>
<?php
$this->headScript()->appendFile(
  $this->apiWebroot . '/public/js/common/common.ajaxapi.js');
$this->headScript()->appendFile(
  $this->moduleWebroot . '/public/js/index/'.$this->moduleName.'.index.js');
?>
<link type="text/css" rel="stylesheet" href="<?php echo $this->moduleWebroot.'/public/css/'.$this->moduleName ?>.css" />
<link type="text/css" rel="stylesheet" href="<?php echo $this->moduleWebroot.'/public/css/'.$this->moduleName ?>.index.css" />
<div class="viewMain">
  <img src="<?php echo $this->moduleWebroot.'/public/images/slicerlogo.png' ?>" />
  <h3>Download packages</h3>
  <div>
<?php
  $osMapping = array('win' => 'Windows', 'macosx' => 'Mac OSX', 'linux' => 'GNU/Linux');
  $archMapping = array('i386' => '32-bit', 'amd64' => '64-bit');
  $firstReleaseFolder = true;
  foreach($this->packageSets as $folderName => $packageSuperset)
    {
    echo '<div class="releaseFolder'.($firstReleaseFolder ? ' firstReleaseFolder' : '').'">';
    echo '  <h3>'.$folderName.'</h3>';
    foreach($packageSuperset as $os => $packageSet)
      {
      echo '  <div class="packageTile">';
      echo '    <div class="packageOS '.$os.'">'.$osMapping[$os].'</div>';
      echo '    <ul class="packageLinks">';
      foreach($packageSet as $name => $package)
        {
        echo '    <li><a href='.$this->webroot.'/download/?items='.$package->getItemId().'>Download '.$archMapping[$package->getArch()].'</a></li>';
        }
      echo '    </ul>';
      echo '  </div>';
      }
    $firstReleaseFolder = false;
    echo '</div>';
    }
?>
  </div>
</div>

<?php echo $this->render('index/viewsidebar.phtml'); ?>
