<?php
/*=========================================================================
MIDAS Server
Copyright (c) Kitware SAS. 20 rue de la Villette. All rights reserved.
69328 Lyon, FRANCE.

See Copyright.txt for details.
This software is distributed WITHOUT ANY WARRANTY; without even
the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR
PURPOSE.  See the above copyright notices for more information.
=========================================================================*/
?>
<?php
$this->headScript()->appendFile(
  $this->apiWebroot . '/public/js/common/common.ajaxapi.js');
$this->headScript()->appendFile(
  $this->moduleWebroot . '/public/js/jquery.tablesorter.js');
$this->headScript()->appendFile(
  $this->moduleWebroot . '/public/js/jquery.client.js');
$this->headScript()->appendFile(
  $this->moduleWebroot . '/public/js/index/slicerpackages.advanced.js');
?>
<link type="text/css" rel="stylesheet" href="<?php echo $this->moduleWebroot.'/public/css/'.$this->moduleName ?>.css" />
<link type="text/css" rel="stylesheet" href="<?php echo $this->moduleWebroot.'/public/css/'.$this->moduleName ?>.advanced.css" />
<link type="text/css" rel="stylesheet" href="<?php echo $this->moduleWebroot?>/public/css/style.css" />
<div class="viewMain">
  <!--<h3>Search packages</h3>-->
  <div>
    <form id="osRaidos">
      <h4>Operating System</h4>
      <span class="choice">
        <input type="radio" name="osGroup" value="any" checked><span class="any">Any</span>
      </span>
      <span class="choice">
        <input type="radio" name="osGroup" value="linux"><span class="linux">GNU/Linux</span>
      </span>
      <span class="choice">
        <input type="radio" name="osGroup" value="macosx"><span class="macosx">Mac OSX</span>
      </span>
      <span class="choice">
        <input type="radio" name="osGroup" value="win"><span class="win">Windows</span>
      </span>
    </form>
    <form id="archRadios">
      <h4>Architecture</h4>
      <span class="choice">
        <input type="radio" name="archGroup" value="any" checked>Any
      </span>
      <span class="choice">
        <input type="radio" name="archGroup" value="i386">32-bit
      </span>
      <span class="choice">
        <input type="radio" name="archGroup" value="amd64">64-bit
      </span>
    </form>
    <form id="buildtypeRadios">
      <h4>Build Type</h4>
      <span class="choice">
        <input type="radio" name="buildGroup" value="any" checked>Any
      </span>
      <?php
      foreach($this->folders as $folder)
        {
        echo '<span class="choice">';
        echo '  <input type="radio" name="buildGroup" value="'.strtolower($folder).'">'.$folder;
        echo '</span>';
        }
      ?>
    </form>
  </div>
  <table id="dataTable" class="tablesorter">
    <thead>
      <tr>
        <th>Package Name</th>
        <th>OS</th>
        <th>Arch</th>
        <th>Type</th>
        <th>Revision</th>
      </tr>
    </thead>
    <tbody id="dataTableContent">
    </tbody>
  </table>
  <div id="dataTableLoading">
    <img alt="" src="<?php echo  $this->coreWebroot?>/public/images/icons/loading.gif" />
  </div>
</div>

<?php echo $this->render('index/viewsidebar.phtml') ?>
